// AstroData.ts

export const zodiacData = [
  {
    id: 1,
    name: "Angel Card Reading",
    date: "",
    image: "https://osheenoracle.com/wp-content/uploads/2024/12/card-ppp.jpg",
    description:
      "Receive gentle divine guidance filled with love, clarity, and healing messages from the angelic realm.",
    traits: ["Guidance", "Healing", "Clarity", "Hope", "Light"],
    element: "",
    planet: "",
    symbol: "",
    luckyColor: "",
    luckyNumber: 0,
    compatibility: [],
    benefits: [
      "Connect with your guardian angels",
      "Receive messages of hope and direction",
      "Gain emotional clarity and reassurance",
    ],
    readingIncludes: [
      "Personalized card reading",
      "Spiritual guidance",
      "Healing and clarity messages",
    ],
    strengths: ["Compassion", "Intuition", "Sensitivity"],
    challenges: ["Overthinking", "Self-doubt"],
  },
  {
    id: 2,
    name: "On Call Consultation",
    date: "",
    image: "/images/withcandle.png",
    description:
      "One-on-one spiritual consultation to bring clarity, healing, and solutions from the comfort of your home.",
    traits: ["Clarity", "Support", "Healing", "Guidance"],
    element: "",
    planet: "",
    symbol: "",
    luckyColor: "",
    luckyNumber: 0,
    compatibility: [],
    benefits: [
      "Instant guidance on personal issues",
      "Emotional support and clarity",
      "Practical spiritual solutions",
    ],
    readingIncludes: [
      "Personal consultation",
      "Healing techniques",
      "Guidance for challenges",
    ],
    strengths: ["Empathy", "Problem-solving", "Insight"],
    challenges: ["Overthinking", "Dependence"],
  },
  {
    id: 3,
    name: "Tarot Reading & Guidance",
    date: "",
    image: "/images/aboutglobe.png",
    description:
      "Soulful tarot sessions offering insight, balance, and direction for love, career, and life decisions.",
    traits: ["Insight", "Balance", "Intuition", "Clarity"],
    element: "",
    planet: "",
    symbol: "",
    luckyColor: "",
    luckyNumber: 0,
    compatibility: [],
    benefits: [
      "Understand hidden opportunities",
      "Gain clarity on decisions",
      "Receive balanced guidance for life paths",
    ],
    readingIncludes: [
      "Tarot card reading",
      "Life guidance",
      "Career & relationship insight",
    ],
    strengths: ["Intuition", "Clarity", "Decision-making"],
    challenges: ["Confusion", "Overanalyzing"],
  },
  {
    id: 4,
    name: "Relationship Healing Spells",
    date: "",
    image: "/images/card-hh.jpg",
    description:
      "Healing rituals to restore love, harmony, trust, and emotional balance in relationships.",
    traits: ["Healing", "Love", "Harmony", "Trust"],
    element: "",
    planet: "",
    symbol: "",
    luckyColor: "",
    luckyNumber: 0,
    compatibility: [],
    benefits: [
      "Restore emotional balance",
      "Strengthen connections",
      "Attract love and understanding",
    ],
    readingIncludes: ["Relationship spells", "Trust rebuilding", "Emotional healing"],
    strengths: ["Compassion", "Patience", "Love"],
    challenges: ["Past baggage", "Misunderstandings"],
  },
  {
    id: 5,
    name: "Career Healing Spells",
    date: "",
    image: "/images/resize-gallery2.jpg",
    description:
      "Energy work to remove obstacles, boost confidence, and attract growth and success in career.",
    traits: ["Confidence", "Focus", "Abundance", "Motivation"],
    element: "",
    planet: "",
    symbol: "",
    luckyColor: "",
    luckyNumber: 0,
    compatibility: [],
    benefits: [
      "Overcome professional blockages",
      "Enhance focus and motivation",
      "Attract career opportunities and growth",
    ],
    readingIncludes: ["Career spells", "Motivation boost", "Growth alignment"],
    strengths: ["Ambition", "Focus", "Energy"],
    challenges: ["Stress", "Doubt"],
  },
  {
    id: 6,
    name: "Spell Jars for Success",
    date: "",
    image: "/images/img-1.jpg",
    description:
      "Handcrafted spell jars infused with crystals and intentions to attract abundance and opportunities.",
    traits: ["Manifestation", "Abundance", "Success", "Energy"],
    element: "",
    planet: "",
    symbol: "",
    luckyColor: "",
    luckyNumber: 0,
    compatibility: [],
    benefits: [
      "Attract success and opportunities",
      "Boost confidence",
      "Align energy with goals",
    ],
    readingIncludes: ["Spell jar creation", "Intention setting", "Energy alignment"],
    strengths: ["Manifestation", "Positivity", "Focus"],
    challenges: ["Negativity", "Distractions"],
  },
  {
    id: 7,
    name: "Reiki Healing Sessions",
    date: "",
    image: "/images/youaremagic.jpg",
    description:
      "Energy healing sessions to release blockages and restore peace to mind, body, and soul.",
    traits: ["Healing", "Energy", "Peace", "Balance"],
    element: "",
    planet: "",
    symbol: "",
    luckyColor: "",
    luckyNumber: 0,
    compatibility: [],
    benefits: [
      "Release emotional blockages",
      "Restore harmony",
      "Enhance spiritual well-being",
    ],
    readingIncludes: ["Hands-on or distance Reiki", "Energy balancing", "Spiritual alignment"],
    strengths: ["Calmness", "Healing", "Focus"],
    challenges: ["Emotional fatigue", "Resistance"],
  },
];

export const astrologers = [
  {
    id: 1,
    name: "Priya Sharma",
    experience: "12+ years",
    specialization: "Vedic Astrology & Palmistry",
    rating: 4.9,
    reviews: 1247,
    expertise: [
      "Career Guidance",
      "Relationship Compatibility",
      "Financial Planning",
      "Marriage Prospects",
    ],
    languages: ["Hindi", "English", "Punjabi"],
    image: "/astrologers/priya-sharma.jpg",
    whatsappNumber: "+919876543210",
    about:
      "Renowned Vedic astrologer with 12+ years of experience in helping people find their true path through ancient astrological principles. Specialized in career guidance and relationship compatibility.",
    successRate: "95%",
    clientsHelped: "5000+",
    consultationFee: "₹799",
    responseTime: "Within 15 minutes",
    availability: "24/7",
    skills: [
      "Kundli Analysis",
      "Muhurta",
      "Gemstone Recommendation",
      "Vastu Shastra",
    ],
  },
  {
    id: 2,
    name: "Rajesh Kumar",
    experience: "15+ years",
    specialization: "Numerology & KP Astrology",
    rating: 4.8,
    reviews: 892,
    expertise: [
      "Marriage Compatibility",
      "Business Growth",
      "Health Issues",
      "Legal Matters",
    ],
    languages: ["Hindi", "Tamil", "English", "Telugu"],
    image: "/astrologers/rajesh-kumar.jpg",
    whatsappNumber: "+919876543211",
    about:
      "Expert in numerology and KP astrology system, specializing in accurate predictions and practical solutions for life challenges. Known for precise business and marriage predictions.",
    successRate: "92%",
    clientsHelped: "4200+",
    consultationFee: "₹699",
    responseTime: "Within 20 minutes",
    availability: "24/7",
    skills: [
      "Numerology",
      "KP System",
      "Horary Astrology",
      "Remedial Measures",
    ],
  },
  {
    id: 3,
    name: "Anita Desai",
    experience: "8+ years",
    specialization: "Tarot Reading & Crystal Healing",
    rating: 4.7,
    reviews: 567,
    expertise: [
      "Love Problems",
      "Spiritual Growth",
      "Career Transition",
      "Personal Development",
    ],
    languages: ["English", "Marathi", "Hindi", "Gujarati"],
    image: "/astrologers/anita-desai.jpg",
    whatsappNumber: "+919876543212",
    about:
      "Combining tarot wisdom with crystal healing to provide holistic guidance and transformative solutions for modern life challenges. Special focus on spiritual and personal growth.",
    successRate: "90%",
    clientsHelped: "3000+",
    consultationFee: "₹899",
    responseTime: "Within 10 minutes",
    availability: "24/7",
    skills: [
      "Tarot Reading",
      "Crystal Healing",
      "Meditation Guidance",
      "Energy Healing",
    ],
  },
  {
    id: 4,
    name: "Dr. Vikram Singh",
    experience: "20+ years",
    specialization: "Medical Astrology & Prashna",
    rating: 4.9,
    reviews: 1563,
    expertise: [
      "Health Issues",
      "Medical Astrology",
      "Prashna Kundli",
      "Remedial Astrology",
    ],
    languages: ["Hindi", "English", "Sanskrit"],
    image: "/astrologers/vikram-singh.jpg",
    whatsappNumber: "+919876543213",
    about:
      "Doctorate in Vedic astrology with specialization in medical astrology and Prashna. Known for accurate health predictions and effective remedial solutions.",
    successRate: "96%",
    clientsHelped: "6800+",
    consultationFee: "₹999",
    responseTime: "Within 30 minutes",
    availability: "10 AM - 8 PM",
    skills: [
      "Medical Astrology",
      "Prashna",
      "Mantra Therapy",
      "Yagya Recommendations",
    ],
  },
  {
    id: 5,
    name: "Meera Patel",
    experience: "10+ years",
    specialization: "Love & Relationship Astrology",
    rating: 4.8,
    reviews: 734,
    expertise: [
      "Love Marriage",
      "Relationship Issues",
      "Family Problems",
      "Divorce Guidance",
    ],
    languages: ["Hindi", "English", "Gujarati", "Marathi"],
    image: "/astrologers/meera-patel.jpg",
    whatsappNumber: "+919876543214",
    about:
      "Specialized in love and relationship astrology with proven track record of helping thousands find love and resolve relationship issues. Compassionate and understanding approach.",
    successRate: "94%",
    clientsHelped: "3500+",
    consultationFee: "₹749",
    responseTime: "Within 15 minutes",
    availability: "24/7",
    skills: [
      "Relationship Analysis",
      "Compatibility Matching",
      "Love Remedies",
      "Marriage Counseling",
    ],
  },
  {
    id: 6,
    name: "Arjun Mehta",
    experience: "7+ years",
    specialization: "Career & Business Astrology",
    rating: 4.7,
    reviews: 423,
    expertise: [
      "Career Growth",
      "Business Success",
      "Job Change",
      "Investment Guidance",
    ],
    languages: ["Hindi", "English", "Bengali"],
    image: "/astrologers/arjun-mehta.jpg",
    whatsappNumber: "+919876543215",
    about:
      "Young and dynamic astrologer specializing in career and business predictions. Known for practical advice and modern approach to traditional astrology.",
    successRate: "91%",
    clientsHelped: "2200+",
    consultationFee: "₹649",
    responseTime: "Within 10 minutes",
    availability: "24/7",
    skills: [
      "Career Prediction",
      "Business Horoscope",
      "Financial Astrology",
      "Remedial Solutions",
    ],
  },
];

export const readingPackages = [
  {
    id: 1,
    name: "Basic Reading",
    price: "₹499",
    duration: "30 minutes",
    features: [
      "Basic personality analysis",
      "Current month predictions",
      "General guidance",
      "2 specific questions answered",
    ],
    bestFor: "Quick insights and general guidance",
  },
  {
    id: 2,
    name: "Premium Reading",
    price: "₹999",
    duration: "60 minutes",
    features: [
      "Detailed personality analysis",
      "3 months detailed predictions",
      "Career and relationship guidance",
      "Unlimited questions",
      "Personalized remedies",
    ],
    bestFor: "Comprehensive life analysis",
  },
  {
    id: 3,
    name: "Yearly Package",
    price: "₹4999",
    duration: "Whole year support",
    features: [
      "Complete birth chart analysis",
      "Yearly horoscope 2024",
      "Monthly follow-up sessions",
      "24/7 chat support",
      "Emergency consultation",
      "All remedies included",
    ],
    bestFor: "Year-long guidance and support",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Rahul Verma",
    zodiac: "Aries",
    rating: 5,
    comment:
      "Priya Sharma's guidance transformed my career. Her predictions were accurate and remedies worked wonders!",
    date: "2 weeks ago",
  },
  {
    id: 2,
    name: "Priya Patel",
    zodiac: "Cancer",
    rating: 5,
    comment:
      "Rajesh Kumar helped me through my relationship crisis. His numerology analysis was spot on!",
    date: "1 month ago",
  },
  {
    id: 3,
    name: "Ankit Singh",
    zodiac: "Leo",
    rating: 5,
    comment:
      "Anita's tarot reading gave me clarity during my career transition. Highly recommended!",
    date: "3 weeks ago",
  },
];
